controller_manager:
  ros__parameters:
    update_rate: 60

    robo_controller:
      type: robo_controller/RoboController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robo_controller:
  ros__parameters:
    description_package: armvision_description
    urdf_file: urdf/armvision.urdf
    frequency: 5.0
    damping_ratio: 1.0

